# This workflow will do a clean install of go dependencies, build the source code and run tests across different versions of go

name: Go Integration CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: read # for golangci/golangci-lint-action to fetch pull requests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.22.x, 1.23.x]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Install Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
       

      - name: Checkout rpc-go repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: open-amt-cloud-toolkit/rpc-go
          path: rpc-go
          ref: main

      - name: Checkout console repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: open-amt-cloud-toolkit/console
          path: console
          ref: main

      - name: Set go-wsman-messages dependency to current branch
        run: |
          cd rpc-go
          go mod edit -replace github.com/open-amt-cloud-toolkit/go-wsman-messages=../${{ github.repository }}
          cd ../console
          go mod edit -replace github.com/open-amt-cloud-toolkit/go-wsman-messages=../${{ github.repository }}

      - name: Build rpc-go
        run: |
          cd rpc-go
          go build -o rpc ./cmd/main.go

      - name: Build console
        run: |
          cd console
          CGO_ENABLED=0 go build -o console ./cmd/app/main.go

      - name: Run tests
        run: |
          go test ./...
