# This workflow will do a clean install of go dependencies, build the source code and run tests across different versions of go

name: Go Integration CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: read # for golangci/golangci-lint-action to fetch pull requests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.22.x, 1.23.x]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Install Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
       

      - name: Checkout rpc-go repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          repository: open-amt-cloud-toolkit/rpc-go
          path: rpc-go
          ref: main

      - name: Checkout console repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          repository: open-amt-cloud-toolkit/console
          path: console
          ref: main

      - name: Set go-wsman-messages dependency to current branch
        run: |
          cd rpc-go
          go mod edit -replace github.com/open-amt-cloud-toolkit/go-wsman-messages=../${{ github.repository }}
          cd ../console
          go mod edit -replace github.com/open-amt-cloud-toolkit/go-wsman-messages=../${{ github.repository }}

      - name: Build rpc-go
        run: |
          cd rpc-go
          go build -o rpc ./cmd/main.go

      - name: Build console
        run: |
          cd console
          CGO_ENABLED=0 go build -o console ./cmd/app/main.go

      - name: Run tests
        run: |
          go test ./...
